
%dw 2.0
output application/java 
---
{
  persId : 96,
  lastName : "Daville",
  firstName : "Amee",
  preferredFirstName : "esse",
  middleName : "odit",
  namePrefix : "veniam,",
  nameSuffix : "quia",
  nameDegreeSuffix : "velit",
  addrStatus : "natus",
  addrLine1 : "id",
  addrLine2 : "Ut",
  addrCity : "Manchester",
  addrState : "aliquip",
  addrZip : "",
  addrCountry : "Chile",
  homePhoneStatus : "voluptatem",
  homePhoneNo : "voluptatem",
  workPhoneStatus : "sunt",
  workPhoneNo : "est,",
  faxPhoneStatus : "fugit,",
  faxPhoneNo : "(665)-220-3727",
  emailStatus : "ea",
  emailAddr : "Darell.Smorfit@gmail.com",
  uwEmailAddr : "magni",
  companyName : "Duis",
  companyJob : "ipsam",
  birthDt : |2014-11-03|,
  gender : "male",
  UWstudentNo : "aliqua.",
  UWNetID : "b226d24ea1234b62ad1",
  persAddedByName : "ipsam",
  persAddedDate : |2018-03-19|,
  persUpdDt : |2012-09-11|,
  persContactUpdDt : |2001-09-13|,
  addressUpdDt : |2018-06-16|,
  homePhoneUpdDt : |2011-10-06|,
  workPhoneUpdDt : |2008-06-11|,
  faxPhoneUpdDt : |2012-01-21|,
  emailUpdDt : |2019-09-03|,
  uwEmailUpdDt : |2009-06-26|,
  primaryEmailType : "reprehenderit",
  hasHold : 2,
  PAC : "voluptatem",
  PACltrPrintDt : |2001-09-10|,
  mergeLossPersId : 50,
  mergeWinPersId : 8,
}
